### ISSUE TITLE
Implementarea functionalitatilor 2.2 - 2.6

### ISSUE THREAD

**Issue by vasi334** [AP-MI-2021/lab-567-vasi334#8]

**Comment by vasi334** [comment]
##Todo
- [ ] Ștergerea tuturor cheltuielilor pentru un apartament dat.
- [ ] Adunarea unei valori la toate cheltuielile dintr-o dată citită.
- [ ] Determinarea celei mai mari cheltuieli pentru fiecare tip de cheltuială.
- [ ] Ordonarea cheltuielilor descrescător după sumă.
- [ ] Afișarea sumelor lunare pentru fiecare apartament.

**Comment by vasi334** [comment]
Implementat 1.2 - 1.6
